- name: Ensure NFS packages are installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - nfs-common
    - nfs-kernel-server

- name: Ensure nfs export exist
  file: 'path="{{ item.strip().split()[0] }}" state=directory'
  with_items: "{{ nfs_exports }}"
  notify: restart nfs

- name: /etc/exports configuration.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  register: etc_exports
  notify: restart nfs

- name: Restart NFS
  service:
    name: nfs-kernel-server
    state: restarted
  when: etc_exports.changed

- name: NFS service
  service:
    name: nfs-kernel-server
    state: started
    enabled: yes
  when: nfs_exports|length
